export const mockPokemonList = [
  {
    id: 1,
    name: "Charizard",
    types: ["Fire", "Flying"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 78,
      attack: 84,
      defense: 78,
      "special-attack": 109,
      "special-defense": 85,
      speed: 100,
    },
    abilities: ["Blaze", "Solar Power"],
    moves: ["Flamethrower", "Dragon Claw", "Air Slash", "Earthquake", "Fire Blast", "Solar Beam"],
  },
  {
    id: 2,
    name: "Blastoise",
    types: ["Water"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 79,
      attack: 83,
      defense: 100,
      "special-attack": 85,
      "special-defense": 105,
      speed: 78,
    },
    abilities: ["Torrent", "Rain Dish"],
    moves: ["Hydro Pump", "Ice Beam", "Earthquake", "Flash Cannon", "Surf", "Dark Pulse"],
  },
  {
    id: 3,
    name: "Venusaur",
    types: ["Grass", "Poison"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 80,
      attack: 82,
      defense: 83,
      "special-attack": 100,
      "special-defense": 100,
      speed: 80,
    },
    abilities: ["Overgrow", "Chlorophyll"],
    moves: ["Solar Beam", "Sludge Bomb", "Earthquake", "Sleep Powder", "Synthesis", "Giga Drain"],
  },
  {
    id: 4,
    name: "Pikachu",
    types: ["Electric"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 35,
      attack: 55,
      defense: 40,
      "special-attack": 50,
      "special-defense": 50,
      speed: 90,
    },
    abilities: ["Static", "Lightning Rod"],
    moves: ["Thunderbolt", "Iron Tail", "Quick Attack", "Volt Tackle", "Thunder", "Grass Knot"],
  },
  {
    id: 5,
    name: "Gengar",
    types: ["Ghost", "Poison"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 60,
      attack: 65,
      defense: 60,
      "special-attack": 130,
      "special-defense": 75,
      speed: 110,
    },
    abilities: ["Cursed Body"],
    moves: ["Shadow Ball", "Sludge Bomb", "Focus Blast", "Thunderbolt", "Destiny Bond", "Hypnosis"],
  },
  {
    id: 6,
    name: "Dragonite",
    types: ["Dragon", "Flying"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 91,
      attack: 134,
      defense: 95,
      "special-attack": 100,
      "special-defense": 100,
      speed: 80,
    },
    abilities: ["Inner Focus", "Multiscale"],
    moves: ["Dragon Claw", "Fire Punch", "Earthquake", "Extreme Speed", "Hurricane", "Roost"],
  },
  {
    id: 7,
    name: "Tyranitar",
    types: ["Rock", "Dark"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 100,
      attack: 134,
      defense: 110,
      "special-attack": 95,
      "special-defense": 100,
      speed: 61,
    },
    abilities: ["Sand Stream", "Unnerve"],
    moves: ["Stone Edge", "Crunch", "Earthquake", "Fire Punch", "Ice Punch", "Thunder Punch"],
  },
  {
    id: 8,
    name: "Garchomp",
    types: ["Dragon", "Ground"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 108,
      attack: 130,
      defense: 95,
      "special-attack": 80,
      "special-defense": 85,
      speed: 102,
    },
    abilities: ["Sand Veil", "Rough Skin"],
    moves: ["Earthquake", "Dragon Claw", "Stone Edge", "Fire Fang", "Swords Dance", "Stealth Rock"],
  },
  {
    id: 9,
    name: "Lucario",
    types: ["Fighting", "Steel"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 70,
      attack: 110,
      defense: 70,
      "special-attack": 115,
      "special-defense": 70,
      speed: 90,
    },
    abilities: ["Steadfast", "Inner Focus", "Justified"],
    moves: ["Aura Sphere", "Close Combat", "Meteor Mash", "Extreme Speed", "Swords Dance", "Bone Rush"],
  },
  {
    id: 10,
    name: "Greninja",
    types: ["Water", "Dark"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 72,
      attack: 95,
      defense: 67,
      "special-attack": 103,
      "special-defense": 71,
      speed: 122,
    },
    abilities: ["Torrent", "Protean"],
    moves: ["Water Shuriken", "Dark Pulse", "Ice Beam", "Gunk Shot", "U-turn", "Spikes"],
  },
  {
    id: 11,
    name: "Metagross",
    types: ["Steel", "Psychic"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 80,
      attack: 135,
      defense: 130,
      "special-attack": 95,
      "special-defense": 90,
      speed: 70,
    },
    abilities: ["Clear Body", "Light Metal"],
    moves: ["Meteor Mash", "Zen Headbutt", "Earthquake", "Ice Punch", "Thunder Punch", "Bullet Punch"],
  },
  {
    id: 12,
    name: "Hydreigon",
    types: ["Dark", "Dragon"],
    sprite: "/placeholder.svg?height=120&width=120",
    stats: {
      hp: 92,
      attack: 105,
      defense: 90,
      "special-attack": 125,
      "special-defense": 90,
      speed: 98,
    },
    abilities: ["Levitate"],
    moves: ["Dark Pulse", "Dragon Pulse", "Fire Blast", "Flash Cannon", "Earth Power", "Draco Meteor"],
  },
]
