import { Pokemon, Ivs, Evs, Stats, Moves, Ability } from "./types"
// This file contains mock data for Pokémon, including their abilities, stats, moves, and other attributes.
// This mock data is used for testing and development purposes in the Pokémon Battler application.

export const mockPokemonList = [
  new Pokemon(
    1,
    "Charizard",
    null,
    [new Ability("Blaze", "This is an ability"), new Ability("Solar Power", "This is an ability")],
    100,
    "Male",
    "Hardy",
    false,
    ["Fire", "Flying"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 78),
      new Stats("attack", 84),
      new Stats("defense", 78),
      new Stats("special-attack", 109),
      new Stats("special-defense", 85),
      new Stats("speed", 100),
    ],
    [
      new Moves("Flamethrower", "Fire", 90, 100, 15, "special"),
      new Moves("Dragon Claw", "Dragon", 80, 100, 15, "physical"),
      new Moves("Air Slash", "Flying", 75, 95, 15, "special"),
      new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
      new Moves("Fire Blast", "Fire", 110, 85, 5, "special"),
      new Moves("Solar Beam", "Grass", 120, 100, 10, "special"),
    ],
    [new Moves("Flamethrower", "Fire", 1000, 100, 15, "special"),
    new Moves("Dragon Claw", "Dragon", 80, 100, 15, "physical"),
    new Moves("Air Slash", "Flying", 0, 95, 15, "special"),
    new Moves("Fire Blast", "Fire", 110, 85, 5, "special")],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png"
  ),
  new Pokemon(
    2,
    "Blastoise",
    null,
    [new Ability("Torrent", "Boosts the power of Water-type moves when the Pokémon's HP is low."), new Ability("Rain Dish", "The Pokémon gradually regains HP in rain.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Water"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 79),
      new Stats("attack", 83),
      new Stats("defense", 100),
      new Stats("special-attack", 85),
      new Stats("special-defense", 105),
      new Stats("speed", 78),
    ],
    [
      new Moves("Hydro Pump", "Water", 110, 80, 5, "special"),
      new Moves("Ice Beam", "Ice", 90, 100, 10, "special"),
      new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
      new Moves("Flash Cannon", "Steel", 80, 100, 10, "special"),
      new Moves("Surf", "Water", 90, 100, 15, "special"),
      new Moves("Dark Pulse", "Dark", 80, 100, 15, "special"),
    ],
    [new Moves("Hydro Pump", "Water", 110, 80, 5, "special"),
    new Moves("Ice Beam", "Ice", 90, 100, 10, "special"),
    new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
    new Moves("Flash Cannon", "Steel", 80, 100, 10, "special"),],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/9.png"
  ),
  new Pokemon(
    3,
    "Venusaur",
    null,
    [new Ability("Overgrow", "Boosts the power of Grass-type moves when the Pokémon's HP is low."), new Ability("Chlorophyll", "Boosts the Pokémon's Speed stat in sunshine.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Grass", "Poison"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 80),
      new Stats("attack", 82),
      new Stats("defense", 83),
      new Stats("special-attack", 100),
      new Stats("special-defense", 100),
      new Stats("speed", 80),
    ],
    [
      new Moves("Solar Beam", "Grass", 120, 100, 10, "special"),
      new Moves("Sludge Bomb", "Poison", 90, 100, 10, "special"),
      new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
      new Moves("Sleep Powder", "Grass", 0, 75, 15, "Status"),
      new Moves("Synthesis", "Grass", 0, 0, 5, "Status"),
      new Moves("Giga Drain", "Grass", 75, 100, 10, "special"),
    ],
    [new Moves("Solar Beam", "Grass", 120, 100, 10, "special"),
    new Moves("Sludge Bomb", "Poison", 70, 100, 10, "special"),
    new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
    new Moves("Sleep Powder", "Grass", 0, 75, 15, "Status")],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/3.png"
  ),
  new Pokemon(
    4,
    "Pikachu",
    null,
    [new Ability("Static", "This is an ability"), new Ability("Lightning Rod", "This is an ability")],
    100,
    "Male",
    "Hardy",
    false,
    ["Electric"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 35),
      new Stats("attack", 55),
      new Stats("defense", 40),
      new Stats("special-attack", 50),
      new Stats("special-defense", 50),
      new Stats("speed", 90),
    ],
    [
      new Moves("Thunderbolt", "Electric", 90, 100, 15, "special"),
      new Moves("Iron Tail", "Steel", 100, 75, 15, "physical"),
      new Moves("Quick Attack", "Normal", 40, 100, 30, "physical"),
      new Moves("Volt Tackle", "Electric", 120, 100, 15, "physical"),
      new Moves("Thunder", "Electric", 110, 70, 10, "special"),
      new Moves("Grass Knot", "Grass", 0, 100, 20, "special"),
    ],
    [new Moves("Thunderbolt", "Electric", 90, 100, 15, "special"),
    new Moves("Iron Tail", "Steel", 100, 75, 15, "physical"),
    new Moves("Quick Attack", "Normal", 40, 100, 30, "physical"),
    new Moves("Volt Tackle", "Electric", 120, 100, 15, "physical")],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png",
  ),
  new Pokemon(
    5,
    "Gengar",
    null,
    [new Ability("Cursed Body", "May disable a move used on the Pokémon.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Ghost", "Poison"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 60),
      new Stats("attack", 65),
      new Stats("defense", 60),
      new Stats("special-attack", 130),
      new Stats("special-defense", 75),
      new Stats("speed", 110),
    ],
    [
      new Moves("Shadow Ball", "Ghost", 80, 100, 15, "special"),
      new Moves("Sludge Bomb", "Poison", 90, 100, 10, "special"),
      new Moves("Focus Blast", "Fighting", 120, 70, 5, "special"),
      new Moves("Thunderbolt", "Electric", 90, 100, 15, "special"),
      new Moves("Destiny Bond", "Ghost", 0, 0, 5, "Status"),
      new Moves("Hypnosis", "Psychic", 0, 60, 20, "Status"),
    ],
    [null, null, null, null],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/94.png"
  ),
  new Pokemon(
    6,
    "Dragonite",
    null,
    [new Ability("Inner Focus", "The Pokémon is protected from flinching."), new Ability("Multiscale", "Reduces damage when HP is full.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Dragon", "Flying"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 91),
      new Stats("attack", 134),
      new Stats("defense", 95),
      new Stats("special-attack", 100),
      new Stats("special-defense", 100),
      new Stats("speed", 180),
    ],
    [
      new Moves("Dragon Claw", "Dragon", 80, 100, 15, "physical"),
      new Moves("Fire Punch", "Fire", 75, 100, 15, "physical"),
      new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
      new Moves("Extreme Speed", "Normal", 80, 100, 5, "physical"),
      new Moves("Hurricane", "Flying", 110, 70, 10, "special"),
      new Moves("Roost", "Flying", 0, 0, 10, "Status"),
    ],
    [null, null, null, null],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/149.png"
  ),
  new Pokemon(
    7,
    "Tyranitar",
    null,
    [new Ability("Sand Stream", "Summons a sandstorm in battle."), new Ability("Unnerve", "Makes the foe nervous and unable to eat Berries.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Rock", "Dark"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 100),
      new Stats("attack", 134),
      new Stats("defense", 110),
      new Stats("special-attack", 95),
      new Stats("special-defense", 100),
      new Stats("speed", 61),
    ],
    [
      new Moves("Stone Edge", "Rock", 100, 80, 5, "physical"),
      new Moves("Crunch", "Dark", 80, 100, 15, "physical"),
      new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
      new Moves("Fire Punch", "Fire", 75, 100, 15, "physical"),
      new Moves("Ice Punch", "Ice", 75, 100, 15, "physical"),
      new Moves("Thunder Punch", "Electric", 75, 100, 15, "physical"),
    ],
    [null, null, null, null],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/248.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/248.png"
  ),
  new Pokemon(
    8,
    "Garchomp",
    null,
    [new Ability("Sand Veil", "Boosts the Pokémon's evasion in a sandstorm."), new Ability("Rough Skin", "Inflicts damage to the attacker on contact.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Dragon", "Ground"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 108),
      new Stats("attack", 130),
      new Stats("defense", 95),
      new Stats("special-attack", 80),
      new Stats("special-defense", 85),
      new Stats("speed", 102),
    ],
    [
      new Moves("Earthquake", "Ground", 100, 100, 10, "physical"),
      new Moves("Dragon Claw", "Dragon", 80, 100, 15, "physical"),
      new Moves("Stone Edge", "Rock", 100, 80, 5, "physical"),
      new Moves("Fire Fang", "Fire", 65, 95, 15, "physical"),
      new Moves("Swords Dance", "Normal", 0, 0, 20, "Status"),
      new Moves("Stealth Rock", "Rock", 0, 0, 20, "Status"),
    ],
    [null, null, null, null],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/445.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/445.png"
  ),
  new Pokemon(
    9,
    "Lucario",
    null,
    [new Ability("Steadfast", "Boosts the Speed stat each time the Pokémon flinches."), new Ability("Inner Focus", "The Pokémon is protected from flinching."), new Ability("Justified", "Boosts the Attack stat when hit by a Dark-type move.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Fighting", "Steel"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 70),
      new Stats("attack", 110),
      new Stats("defense", 70),
      new Stats("special-attack", 115),
      new Stats("special-defense", 70),
      new Stats("speed", 90),
    ],
    [
      new Moves("Aura Sphere", "Fighting", 80, 100, 20, "special"),
      new Moves("Close Combat", "Fighting", 120, 100, 5, "physical"),
      new Moves("Meteor Mash", "Steel", 90, 90, 10, "physical"),
      new Moves("Extreme Speed", "Normal", 80, 100, 5, "physical"),
      new Moves("Swords Dance", "Normal", 0, 0, 20, "Status"),
      new Moves("Bone Rush", "Ground", 25, 90, 10, "physical"),
    ],
    [null, null, null, null],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/448.png"
  ),
  new Pokemon(
    10,
    "Greninja",
    null,
    [new Ability("Torrent", "Boosts the power of Water-type moves when the Pokémon's HP is low."), new Ability("Protean", "Changes the Pokémon's type to the type of the move it uses.")],
    100,
    "Male",
    "Hardy",
    false,
    ["Water", "Dark"],
    [
      new Ivs("hp", 31),
      new Ivs("attack", 31),
      new Ivs("defense", 31),
      new Ivs("special-attack", 31),
      new Ivs("special-defense", 31),
      new Ivs("speed", 31),
    ],
    [
      new Evs("hp", 0),
      new Evs("attack", 0),
      new Evs("defense", 0),
      new Evs("special-attack", 0),
      new Evs("special-defense", 0),
      new Evs("speed", 0),
    ],
    [
      new Stats("hp", 72),
      new Stats("attack", 95),
      new Stats("defense", 67),
      new Stats("special-attack", 103),
      new Stats("special-defense", 71),
      new Stats("speed", 122),
    ],
    [
      new Moves("Water Shuriken", "Water", 15, 100, 20, "special"),
      new Moves("Hydro Pump", "Water", 110, 80, 5, "special"),
      new Moves("Ice Beam", "Ice", 90, 100, 10, "special"),
      new Moves("Dark Pulse", "Dark", 80, 100, 15, "special"),
      new Moves("U-turn", "Bug", 70, 100, 20, "physical"),
      new Moves("Grass Knot", "Grass", 0, 100, 20, "special"),
    ],
    [null, null, null, null],
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/658.png",
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/658.png"
  ),
]
